# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14yTvZUTvtBEd8YjPHhwUnZbjZWLOA6pJ
"""

import streamlit as st
import ast
import traceback

# Configuración de la página de Streamlit
st.set_page_config(
    page_title="CodeSense AI: Analizador de Sintaxis de Python",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Estilos CSS para mejorar la estética
st.markdown("""
<style>
    /* Estilo del título principal */
    .big-font {
        font-size:30px !important;
        font-weight: bold;
        color: #FF4B4B; /* Rojo de Streamlit para el acento */
    }
    /* Estilo para los mensajes de éxito */
    .success-box {
        background-color: #d4edda;
        color: #155724;
        border: 1px solid #c3e6cb;
        padding: 15px;
        border-radius: 5px;
    }
    /* Estilo para los mensajes de error */
    .error-box {
        background-color: #f8d7da;
        color: #721c24;
        border: 1px solid #f5c6cb;
        padding: 15px;
        border-radius: 5px;
    }
    /* Estilo para el área de código */
    .stTextArea > label {
        font-weight: bold;
        font-size: 1.1em;
    }
</style>
""", unsafe_allow_html=True)


def analyze_code(code_input: str):
    """
    Analiza la sintaxis del código Python usando la librería 'ast'
    (Abstract Syntax Tree) para detectar errores sin ejecutar el código.
    """
    if not code_input.strip():
        return False, "Por favor, introduce código Python para analizar.", None

    try:
        # Intenta parsear el código a un Árbol de Sintaxis Abstracta (AST).
        # Esto falla inmediatamente si hay un error de sintaxis (SyntaxError).
        ast.parse(code_input)

        # Si el parseo es exitoso, la sintaxis es correcta.
        return True, "¡Sintaxis Correcta! Este fragmento de código está bien escrito. ¡Añádelo a tu proyecto!", None

    except SyntaxError as e:
        # Si ocurre un SyntaxError, lo capturamos.
        error_message = f"Error de Sintaxis detectado en la línea {e.lineno}:\n\n{e.msg}"
        details = traceback.format_exc() # Para ver el detalle completo en la consola (opcional)
        return False, error_message, details

    except Exception as e:
        # Captura otros errores (ej. tabulaciones inconsistentes)
        error_message = f"Error inesperado durante el análisis: {e}"
        details = traceback.format_exc()
        return False, error_message, details


# --- TÍTULO Y DESCRIPCIÓN ---
st.markdown('<p class="big-font">CodeSense AI 🐍: Analizador de Sintaxis</p>', unsafe_allow_html=True)
st.write("Herramienta rápida para verificar si un fragmento de código Python tiene errores de sintaxis antes de añadirlo a tu repositorio.")
st.write("---")

# --- ÁREA DE ENTRADA DE CÓDIGO ---
# El usuario ingresa el código en este Text Area
code_input = st.text_area(
    "Pega tu fragmento de código Python aquí:",
    height=250,
    value="""# Ejemplo de código correcto:
def saludar(nombre):
    print(f"Hola, {nombre}!")

# Ejemplo de código con error de sintaxis:
# def calcular_area(radio)
#   return 3.14 * radio**2
"""
)

# --- BOTÓN DE ANÁLISIS ---
if st.button("Analizar Código", type="primary"):
    is_correct, message, details = analyze_code(code_input)

    # --- RESULTADO ---
    st.write("## Resultado del Análisis")

    if is_correct:
        # Si la sintaxis es correcta
        st.markdown(
            f'<div class="success-box">{message}</div>',
            unsafe_allow_html=True
        )
        st.balloons() # Animación de éxito
        st.success("¡Tu código está listo para el repositorio!")
    else:
        # Si hay un error de sintaxis
        st.markdown(
            f'<div class="error-box">🚨 ERROR DE SINTAXIS 🚨</div>',
            unsafe_allow_html=True
        )
        st.warning(message)
        st.error("¡Detente! No subas este código. Corrige el error antes de continuar.")

        # Mostrar la línea del error para ayudar al usuario
        if "línea" in message:
            try:
                line_number = int(message.split("línea ")[-1].split(":")[0])
                st.info(f"El error probablemente se encuentra cerca de la línea **{line_number}**.")
            except:
                pass

st.write("---")
st.caption("Desarrollado con Streamlit y la librería nativa 'ast' de Python.")g